### ISSUE TITLE
Name suggestion

### ISSUE THREAD

**Issue by hypesystem** [ath88/mailgun-mustache-mailer#1]
demailer

**Comment by ath88** [comment]
demailer? What is the reasoning behind? :)

**Comment by ath88** [comment]
@hypesystem ping

**Comment by hypesystem** [comment]
just a more "brandy" name than the current (long) name :D

**Comment by ath88** [comment]
Sure - but this is just a utility tool. I'd rather brand the [email-service](https://github.com/ath88/email-service). :)
